### ISSUE TITLE
How to setup a bot to resolve error... "code": 20002, "message": "Only bots can use this endpoint"

### ISSUE THREAD

**Issue by op6sie** [shibdib/EVE-Discord-Bot#61]
Stack trace:
#0 /var/www/EVE-Discord-Bot/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /var/www/EVE-Discord-Bot/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /var/www/EVE-Discord-Bot/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#3 /var/www/EVE-Discord-Bot/vendor/guzzlehttp/promises/src/TaskQueue.php(61): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 /var/www/EVE-Discord-Bot/ in /var/www/EVE-Discord-Bot/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 107
PHP Warning:  Invalid argument supplied for foreach() in /var/www/EVE-Discord-Bot/plugins/tick/getKillmails.php on line 144
PHP Fatal error:  Uncaught exception 'GuzzleHttp\Exception\ClientException' with message 'Client error: `GET https://discordapp.com/api/users/184454011032698880` resulted in a `403 FORBIDDEN` response:
{"code": 20002, "message": "Only bots can use this endpoint"}
' in /var/www/EVE-Discord-Bot/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:107

**Comment by shibdib** [comment]
this will be fixed in the new bot

https://github.com/shibdib/Dramiel

Not yet ready for release

**Comment by op6sie** [comment]
Thanks
Op 26 jun. 2016 6:29 a.m. schreef "shibdib" <notifications@github.com>:
